MODEL: "resnet50"
CAM: "GradCAM"
CAM_PATH: "/content/drive/MyDrive/outputs/mask"
CLASSES: 3
LR: 0.00006
DESIRED_ACCURACY: 0.5
TRANSFER_LEARNING: True
CHECKPOINT_PATH : "/content/drive/MyDrive/weights/mask"
LOAD_CHECKPOINT: False
PARALLEL: False
TRAIN_PATH: "/content/Splitted/train"
VALIDATION_PATH: "/content/Splitted/val"
IMAGE_SIZE: 224
NUM_OF_WORKERS: 2
BATCH_SIZE: 64
LABEL_SMOOTHING: 0.1
MAX_EPOCHS: 1000
THRESHOLD_EPOCH: 100
T_MAX_COEFFICIENT: 10
GPU: 0