MODEL: "vgg16"
CAM: ["GradCAM", "GradCAMpp"] # refer to https://github.com/frgfm/torch-cam
CAM_PATH: "/home/arisa/x_ai/outputs/polyp"
SEGMENTS_PATH: "/home/arisa/x_ai/dataset/polyp/masks"
CLASSES: 2
LR: 0.00005
DESIRED_ACCURACY: 0.60
TRANSFER_LEARNING: True
CHECKPOINT_PATH : "/home/arisa/x_ai/weights/polyp"
LOAD_CHECKPOINT: True
TRAIN_PATH: "/home/arisa/x_ai/dataset/polyp/train"
VALIDATION_PATH: "/home/arisa/x_ai/dataset/polyp/validation"
IMAGE_SIZE: 384
NUM_OF_WORKERS: 2
BATCH_SIZE: 16
LABEL_SMOOTHING: 0.1
MAX_EPOCHS: 1000
THRESHOLD_EPOCH: 100
T_MAX_COEFFICIENT: 10
BASE_LR: 0.000000000001
GPU: 0
HEATMAP_THRESH: 100
TENSORBOARD: "classification" # address to save runs
MODE: "MIX" # choose from 'LRP', 'CAM', 'MIX'
LRP_RULE: ["alpha2beta1", "epsilon"] # refer to https://github.com/fhvilshoj/TorchLRP
VOTING: "max" # choose from 'min', 'max'